/**
 * @file parameters_menu.h Файл меню параметров.
 */

#ifndef PARAMETERS_MENU_H
#define PARAMETERS_MENU_H

#include "menu/menu.h"
#include "localization/localization.h"
#include "translations_ids.h"


/*
 * Перечисления типов для выбора в меню.
 */
//! Перечисление фаз.
MENU_VALUES(menu_enum_phases,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PHASE_UNK)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PHASE_A)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PHASE_B)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PHASE_C))
);
//! Перечисление Да/Нет.
MENU_VALUES(menu_enum_bool,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_NO)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_YES))
);
//! Перечисление режима возбуждения.
MENU_VALUES(menu_enum_exc_mode,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_EXC_MODE_FIXED)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_EXC_MODE_REGULATED))
);
//! Перечисление типа останова.
MENU_VALUES(menu_enum_stop_mode,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_STOP_MODE_NORMAL)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_STOP_MODE_FAST)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_STOP_MODE_COAST))
);
//! Перечисление действия защиты.
MENU_VALUES(menu_enum_prot_action,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PROT_ACTION_IGNORE)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PROT_ACTION_WARNING)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PROT_ACTION_FAST_STOP)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PROT_ACTION_COAST_STOP)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_PROT_ACTION_EMERGENCY_STOP))
);
//! Перечисление типа цифровых входов.
MENU_VALUES(menu_enum_dio_in_type,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_NONE)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_START_STOP)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_EMERGENCY_STOP)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_REFERENCE_INC)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_REFERENCE_DEC)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_CLEAR_ERRORS)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_IN_USER))
);
//! Перечисление типа цифровых выходов.
MENU_VALUES(menu_enum_dio_out_type,
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_NONE)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_OK)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_READY)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_RUNNING)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_ERROR)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_WARNING)),
    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_DIO_OUT_USER))
);

//! Перечисление .
//MENU_VALUES(menu_enum_,
//    MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_)), MAKE_MENU_VALUE_STRING(TEXT(TR_ID_ENUM_))
//);


// Макрос для определения числа элементов перечисления.
#define MENU_ENUM_LEN(MVARR) (sizeof(MVARR)/sizeof(menu_value_t))

/*
 * Значения перечислений элементов меню.
 */
MENU_VALUE_ENUM(menu_val_phase, 0, MENU_ENUM_LEN(menu_enum_phases), menu_enum_phases);
MENU_VALUE_ENUM(menu_val_bool, 0, MENU_ENUM_LEN(menu_enum_bool), menu_enum_bool);
MENU_VALUE_ENUM(menu_val_exc_mode, 0, MENU_ENUM_LEN(menu_enum_exc_mode), menu_enum_exc_mode);
MENU_VALUE_ENUM(menu_val_stop_mode, 0, MENU_ENUM_LEN(menu_enum_stop_mode), menu_enum_stop_mode);
MENU_VALUE_ENUM(menu_val_prot_action, 0, MENU_ENUM_LEN(menu_enum_prot_action), menu_enum_prot_action);
MENU_VALUE_ENUM(menu_val_dio_in_type, 0, MENU_ENUM_LEN(menu_enum_dio_in_type), menu_enum_dio_in_type);
MENU_VALUE_ENUM(menu_val_dio_out_type, 0, MENU_ENUM_LEN(menu_enum_dio_out_type), menu_enum_dio_out_type);

//MENU_VALUE_ENUM(menu_val_, 0, MENU_ENUM_LEN(menu_enum_), menu_enum_);

#undef MENU_ENUM_LEN


/*
 * Дескрипторы элементов меню.
 */
MENU_DESCRS(menu_descrs) {
    // Питание.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_POWER), 0, 0, 0),
        // Сеть.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_POWER_IN), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_U_NOM, TEXT(TR_ID_MENU_U_NOM), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_I_NOM, TEXT(TR_ID_MENU_I_NOM), MENU_FLAG_DATA, 0, 0),
        // Якорь.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_ROTOR), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_U_ROT_NOM, TEXT(TR_ID_MENU_U_ROT_NOM), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_I_ROT_NOM, TEXT(TR_ID_MENU_I_ROT_NOM), MENU_FLAG_DATA, 0, 0),
        // Возбуждение.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_EXCITATION), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_I_EXC, TEXT(TR_ID_MENU_I_EXC), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PHASE, TEXT(TR_ID_MENU_EXC_PHASE), MENU_FLAG_DATA, 0, &menu_val_phase),
            MENU_DESCR(2, PARAM_ID_EXC_MODE, TEXT(TR_ID_MENU_EXC_MODE), MENU_FLAG_DATA, 0, &menu_val_exc_mode),
    // Разгон.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_RAMP), 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_START_TIME, TEXT(TR_ID_MENU_RAMP_START_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_STOP_TIME, TEXT(TR_ID_MENU_RAMP_STOP_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_FAST_STOP_TIME, TEXT(TR_ID_MENU_RAMP_FAST_STOP_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_REFERENCE_TIME, TEXT(TR_ID_MENU_RAMP_REFERENCE_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_RAMP_STOP_MODE, TEXT(TR_ID_MENU_RAMP_STOP_MODE), MENU_FLAG_DATA, 0, &menu_val_stop_mode),
    // ПИД.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_PID), 0, 0, 0),
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_PID_ROT), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_ROT_PID_K_P, TEXT(TR_ID_MENU_PID_K_P), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_ROT_PID_K_I, TEXT(TR_ID_MENU_PID_K_I), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_ROT_PID_K_D, TEXT(TR_ID_MENU_PID_K_D), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_PID_EXC), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PID_K_P, TEXT(TR_ID_MENU_PID_K_P), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PID_K_I, TEXT(TR_ID_MENU_PID_K_I), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_EXC_PID_K_D, TEXT(TR_ID_MENU_PID_K_D), MENU_FLAG_DATA, 0, 0),
    // Запуск и останов.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_START_STOP), 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_ROT_STOP_TIME, TEXT(TR_ID_MENU_ROT_STOP_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_EXC_STOP_TIME, TEXT(TR_ID_MENU_EXC_STOP_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_EXC_START_TIME, TEXT(TR_ID_MENU_EXC_START_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_PHASES_CHECK_TIME, TEXT(TR_ID_MENU_PHASES_CHECK_TIME), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_ZERO_SENSOR_TIME, TEXT(TR_ID_MENU_ZERO_SENSOR_TIME), MENU_FLAG_DATA, 0, 0),
    // Тиристоры.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_TRIACS), 0, 0, 0),
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_TRIACS_OPEN_TIME), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_TRIACS_PAIRS_OPEN_TIME, TEXT(TR_ID_MENU_TRIACS_PAIRS_OPEN_TIME), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_TRIAC_EXC_OPEN_TIME, TEXT(TR_ID_MENU_TRIAC_EXC_OPEN_TIME), MENU_FLAG_DATA, 0, 0),
    // Защита.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_PROTECTION), 0, 0, 0),
        // Тепловая защита.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_THERMAL_OVERLOAD_PROT), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_THERMAL_OVERLOAD_PROT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, PARAM_ID_THERMAL_OVERLOAD_PROT_TIME_6I, TEXT(TR_ID_MENU_THERMAL_OVERLOAD_PROT_TIME_6I), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, PARAM_ID_THERMAL_OVERLOAD_PROT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Грибок.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_EMERGENCY_STOP), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_EMERGENCY_STOP_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Напряжение сети.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_POWER_VOLTAGE), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_CUTOFF), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_U_IN_CUTOFF_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_OVERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_OVF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_UNDERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_IN_UDF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Ток сети.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_POWER_CURRENT), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_CUTOFF), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_I_IN_CUTOFF_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_OVERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_OVF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Напряжение якоря.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_ROTOR_VOLTAGE), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_CUTOFF), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_U_ROT_CUTOFF_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_OVERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_OVF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Ток якоря.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_ROTOR_CURRENT), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_CUTOFF), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_I_ROT_CUTOFF_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_OVERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_OVF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Ток возбуждения.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_EXC_CURRENT), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_CUTOFF), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_PROT_I_EXC_CUTOFF_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_OVERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_OVF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_PROT_UNDERFLOW), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_UDF_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
        // Дрейф нуля.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_ZERO_DRIFT), 0, 0, 0),
            // Токи сети.
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_POWER_CURRENT), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_IN_IDLE_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
            // Напряжение якоря.
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_ROTOR_VOLTAGE), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_U_ROT_IDLE_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
            // Ток якоря.
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_ROTOR_CURRENT), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_ROT_IDLE_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
            // Ток возбуждения.
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_EXC_CURRENT), 0, 0, 0),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_ERROR_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_FAULT_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
                MENU_DESCR(3, 0, TEXT(TR_ID_MENU_PROT_WARNING_LEVEL), 0, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_ENABLE, TEXT(TR_ID_MENU_PROT_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_LEVEL_VALUE, TEXT(TR_ID_MENU_PROT_LEVEL), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_LEVEL_TIME_MS, TEXT(TR_ID_MENU_PROT_LEVEL_TIME_MS), MENU_FLAG_DATA, 0, 0),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_LATCH_ENABLE, TEXT(TR_ID_MENU_PROT_LATCH_ENABLE), MENU_FLAG_DATA, 0, &menu_val_bool),
                    MENU_DESCR(4, PARAM_ID_PROT_I_EXC_IDLE_WARN_ACTION, TEXT(TR_ID_MENU_PROT_ACTION), MENU_FLAG_DATA, 0, &menu_val_prot_action),
    // Вычисления.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_CALCULATION), 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALC_PHASE_CURRENT, TEXT(TR_ID_MENU_CALC_PHASE_CURRENT), MENU_FLAG_DATA, 0, &menu_val_phase),
    // Коммуникация.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_COMMUNICATION), 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_MODBUS_BAUD, TEXT(TR_ID_MENU_MODBUS_BAUD), MENU_FLAG_DATA, 0, 0),
    // Цифровые входа/выхода.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_DIGITAL_IO), 0, 0, 0),
        // Цифровые входа.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_DIGITAL_INPUTS), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_INPUT1), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_1_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_1_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_INPUT2), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_2_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_2_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_INPUT3), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_3_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_3_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_INPUT4), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_4_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_4_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_INPUT5), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_5_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_in_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_IN_5_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
        // Цифровые выхода.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_DIGITAL_OUTPUTS), 0, 0, 0),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_OUTPUT1), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_1_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_1_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_OUTPUT2), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_2_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_2_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_OUTPUT3), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_3_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_3_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
            MENU_DESCR(2, 0, TEXT(TR_ID_MENU_DIO_OUTPUT4), 0, 0, 0),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_4_TYPE, TEXT(TR_ID_MENU_DIO_TYPE), MENU_FLAG_DATA, 0, &menu_val_dio_out_type),
                MENU_DESCR(3, PARAM_ID_DIGITAL_OUT_4_INVERSION, TEXT(TR_ID_MENU_DIO_INVERSION), MENU_FLAG_DATA, 0, &menu_val_bool),
        // Параметры цифровых входов/выходов.
        MENU_DESCR(1, 0, TEXT(TR_ID_MENU_DIGITAL_IO_SETTINGS), 0, 0, 0),
            MENU_DESCR(2, PARAM_ID_DIGITAL_IO_DEADTIME_MS, TEXT(TR_ID_MENU_DIGITAL_IO_DEADTIME_MS), MENU_FLAG_DATA, 0, 0),
    // Коэффициенты АЦП.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_ADC_VALUE_MULTS), 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ua, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Ua), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ub, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Ub), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Uc, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Uc), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Urot, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Urot), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ia, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Ia), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ib, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Ib), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ic, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Ic), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Irot, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Irot), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Iexc, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Iexc), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Iref, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Iref), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_VALUE_MULTIPLIER_Ifan, TEXT(TR_ID_MENU_ADC_VALUE_MULT_Ifan), MENU_FLAG_DATA, 0, 0),
    // Калибровочные данные.
    MENU_DESCR(0, 0, TEXT(TR_ID_MENU_CALIBRATION_DATA), 0, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ua, TEXT(TR_ID_MENU_CALIBRATION_DATA_Ua), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ub, TEXT(TR_ID_MENU_CALIBRATION_DATA_Ub), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Uc, TEXT(TR_ID_MENU_CALIBRATION_DATA_Uc), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Urot, TEXT(TR_ID_MENU_CALIBRATION_DATA_Urot), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ia, TEXT(TR_ID_MENU_CALIBRATION_DATA_Ia), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ib, TEXT(TR_ID_MENU_CALIBRATION_DATA_Ib), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ic, TEXT(TR_ID_MENU_CALIBRATION_DATA_Ic), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Irot, TEXT(TR_ID_MENU_CALIBRATION_DATA_Irot), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Iexc, TEXT(TR_ID_MENU_CALIBRATION_DATA_Iexc), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Iref, TEXT(TR_ID_MENU_CALIBRATION_DATA_Iref), MENU_FLAG_DATA, 0, 0),
        MENU_DESCR(1, PARAM_ID_CALIBRATION_DATA_Ifan, TEXT(TR_ID_MENU_CALIBRATION_DATA_Ifan), MENU_FLAG_DATA, 0, 0),
    //MENU_DESCR(0, 0, TEXT(TR_ID_MENU_), 0, 0, 0)
};

#endif // PARAMETERS_MENU_H
