/**
 * @file parameters_list.h Список параметров.
 */

#ifndef PARAMETERS_LIST_H
#define	PARAMETERS_LIST_H

#include "parameters_ids.h"
#include "translations_ids.h"
#include "localization/localization.h"
#include "settings.h"

//! Макрос для сокращения декларации дробного значения fixed32.
#define F32(A, B) fixed32_make_from_fract(A, B)
//! Макрос для сокращения декларации целого значения fixed32.
#define F32I(I) fixed32_make_from_int(I)
//! Макрос для обозначения отсутствующей единицы измерения.
#define NOUNITS (NULL)

// Число реальных параметров.
#define PARAMETERS_REAL_COUNT 378
// Число виртуальных параметров.
#define PARAMETERS_VIRT_COUNT 48
// Общее число параметров.
#define PARAMETERS_COUNT (PARAMETERS_REAL_COUNT + PARAMETERS_VIRT_COUNT)

// Дескрипторы параметров.
PARAM_DESCRS(parameters_descrs, PARAMETERS_COUNT) {
    // Общие параметры.
    PARAM_DESCR(PARAM_ID_U_NOM,           PARAM_TYPE_UINT,      0,       1000,      220,        0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_I_NOM,           PARAM_TYPE_UINT,      0,       1000,      160,        0, TEXT(TR_ID_UNITS_A)),
    
    // Общие параметры - параметры двигателя.
    PARAM_DESCR(PARAM_ID_MOTOR_P_NOM,      PARAM_TYPE_FRACT_10,  F32(1,10), F32I(1000), F32I(10), 0, TEXT(TR_ID_UNITS_KW)),
    PARAM_DESCR(PARAM_ID_MOTOR_RPM_NOM,    PARAM_TYPE_UINT,      100,       10000,      1000,     0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_MOTOR_RPM_MAX,    PARAM_TYPE_UINT,      100,       10000,      1000,     0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_MOTOR_U_ROT_NOM,  PARAM_TYPE_UINT,      100,       600,        220,      0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_MOTOR_I_ROT_NOM,  PARAM_TYPE_FRACT_10,  F32I(0),   F32I(400),  F32I(50), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_MOTOR_U_EXC_NOM,  PARAM_TYPE_UINT,      100,       600,        220,      0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_MOTOR_I_EXC_NOM,  PARAM_TYPE_FRACT_100, F32I(0),   F32I(20),   F32I(1),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_MOTOR_EFF_NOM,    PARAM_TYPE_FRACT_10,  F32I(0),   F32(999,10),F32I(0),  0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_ROT_NOM,  PARAM_TYPE_FRACT_100, F32I(0),   F32I(20),   F32I(0),  0, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_EXC_NOM,  PARAM_TYPE_FRACT_100, F32I(0),   F32I(20),   F32I(0),  0, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_I_ROT_MAX,  PARAM_TYPE_FRACT_10,  F32I(0),   F32I(800),  F32I(100),0, TEXT(TR_ID_UNITS_A)),
    
    // Параметры работы.
    // Вычисления.
    PARAM_DESCR(PARAM_ID_CALC_PHASE_CURRENT,  PARAM_TYPE_UINT,  0,          3,        0,        0, NOUNITS),
    PARAM_DESCR(PARAM_ID_CALC_PHASE_VOLTAGE,  PARAM_TYPE_UINT,  0,          3,        0,        0, NOUNITS),
    PARAM_DESCR(PARAM_ID_CALC_ROT_CURRENT,    PARAM_TYPE_UINT,  0,          1,        0,        0, NOUNITS),
    PARAM_DESCR(PARAM_ID_CALC_ROT_VOLTAGE,    PARAM_TYPE_UINT,  0,          1,        0,        0, NOUNITS),
    PARAM_DESCR(PARAM_ID_CALC_EXC_CURRENT,    PARAM_TYPE_UINT,  0,          1,        0,        0, NOUNITS),
    
    // Регулятор.
    PARAM_DESCR(PARAM_ID_REGULATOR_MODE,  PARAM_TYPE_UINT, DRIVE_REGULATOR_MODE_SPEED, DRIVE_REGULATOR_MODE_TORQUE, DRIVE_REGULATOR_MODE_SPEED, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_EXC_MODE,        PARAM_TYPE_UINT, DRIVE_TRIACS_EXC_FIXED, DRIVE_TRIACS_EXC_EXTERNAL, DRIVE_TRIACS_EXC_REGULATED, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_EXC_PHASE,       PARAM_TYPE_UINT,      PHASE_A, PHASE_C,  PHASE_C, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_I_EXC,           PARAM_TYPE_FRACT_100, F32I(0), F32I(20), F32I(4), 0, TEXT(TR_ID_UNITS_A)),
    
    PARAM_DESCR(PARAM_ID_RAMP_START_TIME,     PARAM_TYPE_FRACT_10, RAMP_TIME_MIN, RAMP_TIME_MAX, RAMP_START_TIME_DEFAULT,     0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_RAMP_STOP_TIME,      PARAM_TYPE_FRACT_10, RAMP_TIME_MIN, RAMP_TIME_MAX, RAMP_STOP_TIME_DEFAULT,      0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_RAMP_FAST_STOP_TIME, PARAM_TYPE_FRACT_10, RAMP_TIME_MIN, RAMP_TIME_MAX, RAMP_FAST_STOP_TIME_DEFAULT, 0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_RAMP_REFERENCE_TIME, PARAM_TYPE_FRACT_10, RAMP_TIME_MIN, RAMP_TIME_MAX, RAMP_REFERENCE_TIME_DEFAULT, 0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_RAMP_STOP_MODE,      PARAM_TYPE_UINT,        0,        2,        0,        0,  NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PHASE_SYNC_ACCURACY,    PARAM_TYPE_FRACT_10,  F32I(0), F32I(10),  F32I(3),     0,  TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_PHASE_SYNC_PLL_PID_K_P, PARAM_TYPE_FRACT_100, F32I(0), F32I(100), F32(15, 1),  0, NOUNITS), // Kp.
    PARAM_DESCR(PARAM_ID_PHASE_SYNC_PLL_PID_K_I, PARAM_TYPE_FRACT_100, F32I(0), F32I(100), F32(15, 10), 0, NOUNITS), // Ki.
    PARAM_DESCR(PARAM_ID_PHASE_SYNC_PLL_PID_K_D, PARAM_TYPE_FRACT_100, F32I(0), F32I(100), F32I(0),     0, NOUNITS), // Kd.
    
    PARAM_DESCR(PARAM_ID_SPD_PID_K_P,     PARAM_TYPE_FRACT_1000, F32I(0), F32I(32), F32(25, 100), 0, NOUNITS), // Kp.
    PARAM_DESCR(PARAM_ID_SPD_PID_K_I,     PARAM_TYPE_FRACT_1000, F32I(0), F32I(32), F32(7, 100),  0, NOUNITS), // Ki.
    PARAM_DESCR(PARAM_ID_SPD_PID_K_D,     PARAM_TYPE_FRACT_1000, F32I(0), F32I(32), F32I(0),      0, NOUNITS), // Kd.
    PARAM_DESCR(PARAM_ID_ROT_PID_K_P,     PARAM_TYPE_FRACT_1000, F32I(0), F32I(32), F32(25, 100), 0, NOUNITS), // Kp.
    PARAM_DESCR(PARAM_ID_ROT_PID_K_I,     PARAM_TYPE_FRACT_1000, F32I(0), F32I(32), F32(7, 100),  0, NOUNITS), // Ki.
    PARAM_DESCR(PARAM_ID_ROT_PID_K_D,     PARAM_TYPE_FRACT_1000, F32I(0), F32I(32), F32I(0),      0, NOUNITS), // Kd.
    PARAM_DESCR(PARAM_ID_EXC_PID_K_P,     PARAM_TYPE_FRACT_100, F32I(0), F32I(320), F32(25, 1),   0, NOUNITS), // Kp.
    PARAM_DESCR(PARAM_ID_EXC_PID_K_I,     PARAM_TYPE_FRACT_100, F32I(0), F32I(320), F32(10, 1),   0, NOUNITS), // Ki.
    PARAM_DESCR(PARAM_ID_EXC_PID_K_D,     PARAM_TYPE_FRACT_100, F32I(0), F32I(320), F32I(0),      0, NOUNITS), // Kd.
    
    PARAM_DESCR(PARAM_ID_ROT_STOP_TIME,   PARAM_TYPE_UINT,      0,       100,       10,           0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_EXC_STOP_TIME,   PARAM_TYPE_UINT,      0,       100,       10,           0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_EXC_START_TIME,  PARAM_TYPE_UINT,      0,       100,       10,           0, TEXT(TR_ID_UNITS_S)),
    
    PARAM_DESCR(PARAM_ID_PHASES_CHECK_TIME,  PARAM_TYPE_UINT,    0,      1000,      100,          0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_ZERO_SENSOR_TIME,   PARAM_TYPE_UINT,    0,      1000,      100,          0, TEXT(TR_ID_UNITS_US)),
    
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_OPEN_TIME,   PARAM_TYPE_UINT,  0,  1000,   200,   0, TEXT(TR_ID_UNITS_US)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_OPEN_TIME,      PARAM_TYPE_UINT,  0,  1000,   200,   0, TEXT(TR_ID_UNITS_US)),
    
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_ANGLE_MIN, PARAM_TYPE_FRACT_100, F32I(0),  F32I(120), F32I(0),   0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_ANGLE_MAX, PARAM_TYPE_FRACT_100, F32I(0),  F32I(120), F32I(115), 0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_ANGLE_MIN,    PARAM_TYPE_FRACT_100, F32I(30), F32I(180), F32I(30),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_ANGLE_MAX,    PARAM_TYPE_FRACT_100, F32I(30), F32I(180), F32I(175), 0, TEXT(TR_ID_UNITS_DEGREE)),
    
    PARAM_DESCR(PARAM_ID_FAN_CONTROL_ENABLE,   PARAM_TYPE_UINT,   0,    1,   1,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_FAN_TEMP_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(100), F32I(30), 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_FAN_TEMP_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(100), F32I(60), 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_FAN_RPM_MIN,  PARAM_TYPE_UINT,           0,  100,  30,   0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_FAN_ECO_MODE_ENABLE,  PARAM_TYPE_UINT,   0,    1,   0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_FAN_ECO_COOLING_TIME, PARAM_TYPE_UINT,   0, 3600,  60,   0, TEXT(TR_ID_UNITS_S)),
    PARAM_DESCR(PARAM_ID_FAN_I_NOM,            PARAM_TYPE_FRACT_100, F32I(0), F32I(2), F32(5,10), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_FAN_I_ZERO_NOISE,     PARAM_TYPE_FRACT_100, F32I(0), F32I(2), F32(1,10), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_FAN_PROT_TIME,        PARAM_TYPE_UINT,            0,   60000,       100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_FAN_PROT_OVF_LEVEL,   PARAM_TYPE_UINT,            0,    1000,        10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    
    // Общая защита.
    PARAM_DESCR(PARAM_ID_EMERGENCY_STOP_ACTION,         PARAM_TYPE_UINT,      0,         4,       4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_THERMAL_OVERLOAD_PROT_ENABLE,  PARAM_TYPE_UINT,      0,         1,       1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_THERMAL_OVERLOAD_PROT_TIME_6I, PARAM_TYPE_FRACT_100, 0, F32I(100), F32I(5), 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_THERMAL_OVERLOAD_PROT_ACTION,  PARAM_TYPE_UINT,      0,         4,       4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_ROT_BREAK_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_ROT_BREAK_VALUE,        PARAM_TYPE_UINT, 0,   600, 100, 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_PROT_ROT_BREAK_TIME_MS,      PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_ROT_BREAK_LATCH_ENABLE, PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_ROT_BREAK_ACTION,       PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_ROT_MEASURE_BREAK_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_ROT_MEASURE_BREAK_VALUE,        PARAM_TYPE_UINT, 0,   400,  10, 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_ROT_MEASURE_BREAK_TIME_MS,      PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_ROT_MEASURE_BREAK_LATCH_ENABLE, PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_ROT_MEASURE_BREAK_ACTION,       PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_PHASES_STATE_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_STATE_TIME_MS,      PARAM_TYPE_UINT, 0, 60000,  40, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_STATE_ACTION,       PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_FAULT_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_FAULT_VALUE,        PARAM_TYPE_UINT, 0,   120,   6, 0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_FAULT_TIME_MS,      PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_FAULT_LATCH_ENABLE, PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_FAULT_ACTION,       PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_WARN_ENABLED,       PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_WARN_VALUE,         PARAM_TYPE_UINT, 0,   120,   3, 0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_WARN_TIME_MS,       PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_WARN_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_ANGLES_WARN_ACTION,        PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_FAULT_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_FAULT_VALUE,        PARAM_TYPE_UINT, 0,   120,   6, 0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_FAULT_TIME_MS,      PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_FAULT_LATCH_ENABLE, PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_FAULT_ACTION,       PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_WARN_ENABLED,       PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_WARN_VALUE,         PARAM_TYPE_UINT, 0,   120,   3, 0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_WARN_TIME_MS,       PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_WARN_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_PHASES_SYNC_WARN_ACTION,        PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_HEATSINK_TEMP_FAULT_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_HEATSINK_TEMP_FAULT_VALUE,        PARAM_TYPE_UINT, 0,   200, 100, 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_PROT_HEATSINK_TEMP_FAULT_ACTION,       PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_HEATSINK_TEMP_WARN_ENABLED,       PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_HEATSINK_TEMP_WARN_VALUE,         PARAM_TYPE_UINT, 0,   200,  80, 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_PROT_HEATSINK_TEMP_WARN_ACTION,        PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    // Защита тиристоров.
    PARAM_DESCR(PARAM_ID_PROT_TRIACS_WARN_ENABLED,      PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_TRIACS_WARN_MIN_ANGLE,    PARAM_TYPE_UINT, 0,   120,  30, 0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_PROT_TRIACS_WARN_MIN_CURRENT,  PARAM_TYPE_FRACT_10, F32I(0), F32I(100), F32I(3), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_TRIACS_WARN_TIME_MS,      PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_TRIACS_WARN_LATCH_ENABLE, PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_TRIACS_WARN_ACTION,       PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    // Защита датчиков.
    // Напряжение сети.
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_IN_ENABLED,           PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_IN_ADC_RANGE_MIN,     PARAM_TYPE_UINT, 0, 4095,  100, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_IN_ADC_RANGE_MAX,     PARAM_TYPE_UINT, 0, 4095, 4000, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_IN_EMULATION_ENABLED, PARAM_TYPE_UINT, 0,    1,    0, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_IN_LATCH_ENABLE,      PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_IN_ACTION,            PARAM_TYPE_UINT, 0,    4,    4, 0, NOUNITS),
    // Ток сети.
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_IN_ENABLED,           PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_IN_ADC_RANGE_MIN,     PARAM_TYPE_UINT, 0, 4095,  100, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_IN_ADC_RANGE_MAX,     PARAM_TYPE_UINT, 0, 4095, 4000, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_IN_EMULATION_ENABLED, PARAM_TYPE_UINT, 0,    1,    0, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_IN_LATCH_ENABLE,      PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_IN_ACTION,            PARAM_TYPE_UINT, 0,    4,    4, 0, NOUNITS),
    // Напряжение якоря.
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_ROT_ENABLED,           PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_ROT_ADC_RANGE_MIN,     PARAM_TYPE_UINT, 0, 4095,  100, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_ROT_ADC_RANGE_MAX,     PARAM_TYPE_UINT, 0, 4095, 4000, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_ROT_EMULATION_ENABLED, PARAM_TYPE_UINT, 0,    1,    0, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_ROT_LATCH_ENABLE,      PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_U_ROT_ACTION,            PARAM_TYPE_UINT, 0,    4,    4, 0, NOUNITS),
    // Ток якоря.
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_ROT_ENABLED,           PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_ROT_ADC_RANGE_MIN,     PARAM_TYPE_UINT, 0, 4095,  100, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_ROT_ADC_RANGE_MAX,     PARAM_TYPE_UINT, 0, 4095, 4000, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_ROT_EMULATION_ENABLED, PARAM_TYPE_UINT, 0,    1,    0, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_ROT_LATCH_ENABLE,      PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_ROT_ACTION,            PARAM_TYPE_UINT, 0,    4,    4, 0, NOUNITS),
    // Ток возбуждения.
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_EXC_ENABLED,           PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_EXC_ADC_RANGE_MIN,     PARAM_TYPE_UINT, 0, 4095,  100, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_EXC_ADC_RANGE_MAX,     PARAM_TYPE_UINT, 0, 4095, 4000, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_EXC_EMULATION_ENABLED, PARAM_TYPE_UINT, 0,    1,    0, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_EXC_LATCH_ENABLE,      PARAM_TYPE_UINT, 0,    1,    1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_SENSORS_I_EXC_ACTION,            PARAM_TYPE_UINT, 0,    4,    4, 0, NOUNITS),
    
    // Защита в работе.
    PARAM_DESCR(PARAM_ID_PROT_U_IN_CUTOFF_LEVEL_VALUE,      PARAM_TYPE_UINT, 0,  1000,  20, 0, TEXT(TR_ID_UNITS_PERCENT)),
    
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_OVF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_IN_UDF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_I_IN_CUTOFF_LEVEL_VALUE,      PARAM_TYPE_UINT, 0,  1000,  20, 0, TEXT(TR_ID_UNITS_PERCENT)),
    
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_OVF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_CUTOFF_LEVEL_VALUE,      PARAM_TYPE_UINT, 0,  1000,  20, 0, TEXT(TR_ID_UNITS_PERCENT)),
    
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_OVF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_CUTOFF_LEVEL_VALUE,      PARAM_TYPE_UINT, 0,  1000,  20, 0, TEXT(TR_ID_UNITS_PERCENT)),
    
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_OVF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_CUTOFF_LEVEL_VALUE,      PARAM_TYPE_UINT, 0,  1000,  20, 0, TEXT(TR_ID_UNITS_PERCENT)),
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_FAULT_ENABLE,        PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_FAULT_LEVEL_VALUE,   PARAM_TYPE_UINT, 0,  1000,  10, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_FAULT_ACTION,        PARAM_TYPE_UINT, 0,     4,   4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_OVF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_WARN_ENABLE,         PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_WARN_LEVEL_VALUE,    PARAM_TYPE_UINT, 0,  1000,   5, 0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT, 0, 60000, 100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT, 0,     1,   1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_UDF_WARN_ACTION,         PARAM_TYPE_UINT, 0,     4,   1, 0, NOUNITS),
    
    // Защита в простое.
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_FAULT_ENABLE,        PARAM_TYPE_UINT,      0,         1,         1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_FAULT_LEVEL_VALUE,   PARAM_TYPE_FRACT_100, 0, F32I(100),  F32I(10), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT,      0,     60000,       100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT,      0,         1,         1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_FAULT_ACTION,        PARAM_TYPE_UINT,      0,         4,         4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_WARN_ENABLE,         PARAM_TYPE_UINT,      0,         1,         1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_WARN_LEVEL_VALUE,    PARAM_TYPE_FRACT_100, 0, F32I(100),   F32I(5), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT,      0,     60000,       100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT,      0,         1,         1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_IN_IDLE_WARN_ACTION,         PARAM_TYPE_UINT,      0,         4,         1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_FAULT_ENABLE,        PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_FAULT_LEVEL_VALUE,   PARAM_TYPE_FRACT_100, 0, F32I(100), F32I(10), 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT,      0,     60000,      100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_FAULT_ACTION,        PARAM_TYPE_UINT,      0,         4,        4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_WARN_ENABLE,         PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_WARN_LEVEL_VALUE,    PARAM_TYPE_FRACT_100, 0, F32I(100),  F32I(5), 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT,      0,     60000,      100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_U_ROT_IDLE_WARN_ACTION,         PARAM_TYPE_UINT,      0,         4,        1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_FAULT_ENABLE,        PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_FAULT_LEVEL_VALUE,   PARAM_TYPE_FRACT_100, 0, F32I(100), F32I(10), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT,      0,     60000,      100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_FAULT_ACTION,        PARAM_TYPE_UINT,      0,         4,        4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_WARN_ENABLE,         PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_WARN_LEVEL_VALUE,    PARAM_TYPE_FRACT_100, 0, F32I(100),  F32I(5), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT,      0,     60000,      100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_ROT_IDLE_WARN_ACTION,         PARAM_TYPE_UINT,      0,         4,        1, 0, NOUNITS),
    
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_FAULT_ENABLE,        PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_FAULT_LEVEL_VALUE,   PARAM_TYPE_FRACT_100, 0, F32I(100),  F32I(1), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_FAULT_LEVEL_TIME_MS, PARAM_TYPE_UINT,      0,     60000,      100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_FAULT_LATCH_ENABLE,  PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_FAULT_ACTION,        PARAM_TYPE_UINT,      0,         4,        4, 0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_WARN_ENABLE,         PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_WARN_LEVEL_VALUE,    PARAM_TYPE_FRACT_100, 0, F32I(100),F32(5,10), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_WARN_LEVEL_TIME_MS,  PARAM_TYPE_UINT,      0,     60000,      100, 0, TEXT(TR_ID_UNITS_MS)),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_WARN_LATCH_ENABLE,   PARAM_TYPE_UINT,      0,         1,        1, 0, NOUNITS),
    PARAM_DESCR(PARAM_ID_PROT_I_EXC_IDLE_WARN_ACTION,         PARAM_TYPE_UINT,      0,         4,        1, 0, NOUNITS),
    
    // Интерфейсы.
    PARAM_DESCR(PARAM_ID_MODBUS_BAUD,     PARAM_TYPE_UINT,  1200,  57600,  9600,  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_MODBUS_ADDRESS,  PARAM_TYPE_UINT,     1,    255,     1,  0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_DIGITAL_IO_DEADTIME_MS,  PARAM_TYPE_UINT,  0, 1000,  100,   0, TEXT(TR_ID_UNITS_MS)),
    
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_1_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_1_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_2_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_2_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_3_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_3_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_4_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_4_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_5_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_5_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_1_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_1_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_2_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_2_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_3_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_3_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_4_TYPE,      PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_4_INVERSION, PARAM_TYPE_UINT,  0,    6,    0,   0, NOUNITS),
    
    // Настройки интерфейса панели (GUI)
    PARAM_DESCR(PARAM_ID_GUI_LANGUAGE,     PARAM_TYPE_UINT, 0,  1,   0,  0,  NOUNITS),        
    PARAM_DESCR(PARAM_ID_MENU_GUI_TILE_WARNINGS,     PARAM_TYPE_UINT, 0,  GUI_HOME_TILES_COUNT,   GUI_HOME_TILES_COUNT,  0,  NOUNITS),
    PARAM_DESCR(PARAM_ID_GUI_TILE_1,       PARAM_TYPE_UINT, GUI_TILE_TYPES_MIN, GUI_TILE_TYPES_MAX,  0,  0,  NOUNITS),  
    PARAM_DESCR(PARAM_ID_GUI_TILE_2,       PARAM_TYPE_UINT, GUI_TILE_TYPES_MIN, GUI_TILE_TYPES_MAX,  1,  0,  NOUNITS), 
    PARAM_DESCR(PARAM_ID_GUI_TILE_3,       PARAM_TYPE_UINT, GUI_TILE_TYPES_MIN, GUI_TILE_TYPES_MAX,  2,  0,  NOUNITS), 
    PARAM_DESCR(PARAM_ID_GUI_TILE_4,       PARAM_TYPE_UINT, GUI_TILE_TYPES_MIN, GUI_TILE_TYPES_MAX,  3,  0,  NOUNITS), 
    PARAM_DESCR(PARAM_ID_GUI_BUZZER,       PARAM_TYPE_UINT, 0,  1,  1,  0,  NOUNITS),
    PARAM_DESCR(PARAM_ID_GUI_PASSWORD_ADMIN,    PARAM_TYPE_UINT, 0,  9999,  0,  0,  NOUNITS),
    PARAM_DESCR(PARAM_ID_GUI_PASSWORD_ROOT,     PARAM_TYPE_UINT, 0,  9999,  0,  0,  NOUNITS),
    
    // GUI: диапазоны индикации WARN и ALARM статусов значений, отображаемых на плитках.
    // Напряжение фазы.
    PARAM_DESCR(PARAM_ID_POWER_U_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(208), 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_WARN_MIN,  PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(219), 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_WARN_MAX,  PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(241), 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(252), 0, TEXT(TR_ID_UNITS_V)),
    // Напряжение якоря.
    PARAM_DESCR(PARAM_ID_POWER_U_ROT_ALARM_MIN, PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_ROT_WARN_MIN,  PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(75),  0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_ROT_WARN_MAX,  PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(125), 0, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_ROT_ALARM_MAX, PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(150), 0, TEXT(TR_ID_UNITS_V)),
    // Ток фазы.
    PARAM_DESCR(PARAM_ID_POWER_I_ALARM_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_WARN_MIN,  PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(75),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_WARN_MAX,  PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(125), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_ALARM_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(150), 0, TEXT(TR_ID_UNITS_A)),
    // Ток якоря.
    PARAM_DESCR(PARAM_ID_POWER_I_ROT_ALARM_MIN, PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_ROT_WARN_MIN,  PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(75),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_ROT_WARN_MAX,  PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(125), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_ROT_ALARM_MAX, PARAM_TYPE_FRACT_10,   F32I(0), F32I(1000), F32I(150), 0, TEXT(TR_ID_UNITS_A)),
    // Ток возбуждения.
    PARAM_DESCR(PARAM_ID_POWER_I_EXC_ALARM_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_EXC_WARN_MIN,  PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(75),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_EXC_WARN_MAX,  PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(125), 0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_EXC_ALARM_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(150), 0, TEXT(TR_ID_UNITS_A)),
    // Температура радиатора.
    PARAM_DESCR(PARAM_ID_HEATSINK_TEMP_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_HEATSINK_TEMP_WARN_MIN,  PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(10), 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_HEATSINK_TEMP_WARN_MAX,  PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(50), 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_HEATSINK_TEMP_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(60), 0, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    // Ток вентилятора.
    PARAM_DESCR(PARAM_ID_POWER_I_FAN_ALARM_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_FAN_WARN_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_FAN_WARN_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_FAN_ALARM_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    // Ток 4-20.
    PARAM_DESCR(PARAM_ID_POWER_I_REF_ALARM_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_REF_WARN_MIN, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_REF_WARN_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_REF_ALARM_MAX, PARAM_TYPE_FRACT_10, F32I(0), F32I(1000), F32I(50),  0, TEXT(TR_ID_UNITS_A)),
    // Обороты вентилятора радиатора.
    PARAM_DESCR(PARAM_ID_HEATSINK_FAN_RPM_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_HEATSINK_FAN_RPM_WARN_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_HEATSINK_FAN_RPM_WARN_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_HEATSINK_FAN_RPM_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_RPM)),
    // Угол открытия тиристоров.
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_OPEN_ANGLE_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_OPEN_ANGLE_WARN_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_OPEN_ANGLE_WARN_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_OPEN_ANGLE_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    // Угол открытия возбуждения.
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_OPEN_ANGLE_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_OPEN_ANGLE_WARN_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_OPEN_ANGLE_WARN_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_OPEN_ANGLE_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(0),  0, TEXT(TR_ID_UNITS_DEGREE)),
    /////////// Мотор //////////// 
    // Вычисленный коэффициент полезного действия.        
    PARAM_DESCR(PARAM_ID_MOTOR_EFF_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(100), F32I(50),  0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_MOTOR_EFF_WARN_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(100), F32I(60),  0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_MOTOR_EFF_WARN_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(100), F32I(100),  0, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_MOTOR_EFF_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(100), F32I(100),  0, TEXT(TR_ID_UNITS_PERCENT)),
    // Вычисленное сопротивление якоря.
    PARAM_DESCR(PARAM_ID_MOTOR_R_ROT_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(10),  0, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_ROT_WARN_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(20),  0, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_ROT_WARN_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(500),  0, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_ROT_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(900),  0, TEXT(TR_ID_UNITS_OHM)),
    // Вычисленные обороты. 
    PARAM_DESCR(PARAM_ID_MOTOR_RPM_ALARM_MIN, PARAM_TYPE_INT,  -30000, 30000, -5000,  0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_MOTOR_RPM_WARN_MIN, PARAM_TYPE_INT,  -30000, 30000, -4000,  0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_MOTOR_RPM_WARN_MAX, PARAM_TYPE_INT,  -30000, 30000, 4000,  0, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_MOTOR_RPM_ALARM_MAX, PARAM_TYPE_INT,  -30000, 30000, 5000,  0, TEXT(TR_ID_UNITS_RPM)),
    // Вычисленный момент.
    PARAM_DESCR(PARAM_ID_MOTOR_TORQUE_ALARM_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(10),  0, TEXT(TR_ID_UNITS_TORQUE)),
    PARAM_DESCR(PARAM_ID_MOTOR_TORQUE_WARN_MIN, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(20),  0, TEXT(TR_ID_UNITS_TORQUE)),
    PARAM_DESCR(PARAM_ID_MOTOR_TORQUE_WARN_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(30),  0, TEXT(TR_ID_UNITS_TORQUE)),
    PARAM_DESCR(PARAM_ID_MOTOR_TORQUE_ALARM_MAX, PARAM_TYPE_FRACT_10,  F32I(0), F32I(1000), F32I(40),  0, TEXT(TR_ID_UNITS_TORQUE)),
                
    // АЦП.
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Ua,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Ub,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Uc,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Urot,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Ia,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Ib,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Ic,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Irot,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Iexc,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Iref,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_VALUE_MULTIPLIER_Ifan,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Ua,    PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Ub,    PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Uc,    PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Urot,  PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Ia,    PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Ib,    PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Ic,    PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Irot,  PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Iexc,  PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Iref,  PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    PARAM_DESCR(PARAM_ID_ADC_CALIBRATION_DATA_Ifan,  PARAM_TYPE_UINT,  0,    4096,     2048,    0, NOUNITS),
    
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Ua,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Ub,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Uc,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Urot,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Ia,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Ib,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Ic,    PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Irot,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Iexc,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Iref,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    PARAM_DESCR(PARAM_ID_VALUE_MULTIPLIER_Ifan,  PARAM_TYPE_FRACT_10000,  0,  F32I(2),  F32I(1),  0, NOUNITS),
    
    // Виртуальные параметры.
            
    // данные питания
    PARAM_DESCR(PARAM_ID_POWER_U_A,   PARAM_TYPE_FRACT_10,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_B,   PARAM_TYPE_FRACT_10,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_C,   PARAM_TYPE_FRACT_10,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_U_ROT, PARAM_TYPE_FRACT_10,   0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_POWER_I_A,   PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_B,   PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_C,   PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_ROT, PARAM_TYPE_FRACT_10,   0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_EXC, PARAM_TYPE_FRACT_1000, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_REF, PARAM_TYPE_FRACT_1000, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_I_FAN, PARAM_TYPE_FRACT_1000, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_A)),
    PARAM_DESCR(PARAM_ID_POWER_CALC_U_ROT, PARAM_TYPE_FRACT_10, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_V)),
    PARAM_DESCR(PARAM_ID_HEATSINK_TEMP,    PARAM_TYPE_FRACT_10, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_DEGREE_CELSIUS)),
    PARAM_DESCR(PARAM_ID_HEATSINK_FAN_RPM, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_TRIACS_PAIRS_OPEN_ANGLE, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_DEGREE)),
    PARAM_DESCR(PARAM_ID_TRIAC_EXC_OPEN_ANGLE,    PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_DEGREE)),
    // данные состояния цифровых входов
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_1_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_2_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_3_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_4_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_IN_5_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    // данные состояния цифровых выходов
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_1_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_2_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_3_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DIGITAL_OUT_4_STATE, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    // Наработка.
    PARAM_DESCR(PARAM_ID_LIFETIME,     PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_HOUR)),
    PARAM_DESCR(PARAM_ID_RUNTIME,      PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_HOUR)),
    PARAM_DESCR(PARAM_ID_FAN_RUNTIME,  PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_HOUR)),
    PARAM_DESCR(PARAM_ID_LAST_RUNTIME, PARAM_TYPE_UINT,     0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_HOUR)),
    // Мотор.
    PARAM_DESCR(PARAM_ID_MOTOR_EFF,    PARAM_TYPE_FRACT_10,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_PERCENT)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_ROT,  PARAM_TYPE_FRACT_100, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_R_EXC,  PARAM_TYPE_FRACT_100, 0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_OHM)),
    PARAM_DESCR(PARAM_ID_MOTOR_RPM,    PARAM_TYPE_INT,       0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_RPM)),
    PARAM_DESCR(PARAM_ID_MOTOR_TORQUE, PARAM_TYPE_FRACT_10,  0, 0, 0, PARAM_FLAG_VIRTUAL, TEXT(TR_ID_UNITS_TORQUE)),
    // Версия прошивки
            
    // Дата время прошивки
    
    // ПИДы.
    PARAM_DESCR(PARAM_ID_PID_PHASE_SYNC, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_PID_EXC_CURRENT, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_PID_ROT_SPEED, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_PID_ROT_CURRENT, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    // Отладка.
    PARAM_DESCR(PARAM_ID_DEBUG_0, PARAM_TYPE_INT,        0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_1, PARAM_TYPE_INT,        0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_2, PARAM_TYPE_UINT,       0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_3, PARAM_TYPE_UINT,       0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_4, PARAM_TYPE_FRACT_10,   0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_5, PARAM_TYPE_FRACT_10,   0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_6, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_7, PARAM_TYPE_FRACT_100,  0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_8, PARAM_TYPE_FRACT_1000, 0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
    PARAM_DESCR(PARAM_ID_DEBUG_9, PARAM_TYPE_FRACT_1000, 0, 0, 0, PARAM_FLAG_VIRTUAL, NOUNITS),
};

#undef NOUNITS
#undef F32I
#undef F32

#endif	/* PARAMETERS_LIST_H */
